name: Hardhat CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./blockchain-project

      - name: Compile smart contracts
        run: npx hardhat compile
        working-directory: ./blockchain-project

      - name: Run tests
        run: npx hardhat test
        working-directory: ./blockchain-project
